export default [
    {
        id: 1,
        name:"Sri Harminder Sahib",
        state:"Punjab",
        stars:"4.9",
        price:"Low",
        city:"Amritsar",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Z29sZGVuJTIwdGVtcGxlfGVufDB8fDB8fHww&w=1000&q=80"
    },
    {
        id: 2,
        name:"Jallianwala Bagh",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Amritsar",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://static.theprint.in/wp-content/uploads/2018/12/Panorama_of_Jallianwala_Bagh-e1550674910748.jpg"
    },
    {
        id: 3,
        name:"The Partition Museum",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Amritsar",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://amritsartourism.org.in/images/places-to-visit/headers/partition-museum-amritsar-tourism-entry-fee-timings-holidays-reviews-header.jpg"
    },
    {
        id: 4,
        name:"Wagah Border",
        state:"Punjab",
        stars:"4.0",
        price:"Low",
        city:"Amritsar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://amritsartourism.org.in/images/places-to-visit/headers/wagah-border-amritsar-tourism-entry-fee-timings-holidays-reviews-header.jpg"
    },
    {
        id: 5,
        name:"Maharaja Ranjit Singh War Museum",
        state:"Punjab",
        stars:"4.3",
        price:"Low",
        city:"Ludhiana",
        crowd:"low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.jagranimages.com/images/newimg/13082022/13_08_2022-maharaj_ranjit_singh_22977151.jpg"
    },
    {
        id: 6,
        name:"Rock Garden",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Chandigarh",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.citywoofer.com/blog/wp-content/uploads/2022/12/WhatsApp-Image-2022-12-13-at-11.34.17-PM.jpeg"
    },
    {
        id: 7,
        name:"Sukhna Lake",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Chandigarh",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.mapsofindia.com/ci-moi-images/my-india/sl-ch-punj-00051.jpg"
    },
    {
        id: 8,
        name:"Zakir Hussain Rose Garden",
        state:"Punjab",
        stars:"4.4",
        price:"Low",
        city:"Chandigarh",
        crowd:"low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/2/22/Rose_Garden_%2CChandigarh%2CIndia.jpg"
    },
    {
        id: 9,
        name:"Elante Mall",
        state:"Punjab",
        stars:"4.5",
        price:"Medium",
        city:"Chandigarh",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://singh-life.com/wp-content/uploads/2021/10/IMG_4781.jpg"
    },
    {
        id: 10,
        name:"Japenese Garden",
        state:"Punjab",
        stars:"4.3",
        price:"Low",
        city:"Chandigarh",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/5/5a/The_Japanese_Garden_Chandigarh_scenery.jpg"
    },
    {
        id: 11,
        name:"Devi Talab Mandir",
        state:"Punjab",
        stars:"4.7",
        price:"Low",
        city:"Jalandhar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn.holidaytravel.co/uploaded_files/destination_img/2016_1657efb450dd59cdevi-talab-jalandhar-tourist-guide.jpg"
    },
    {
        id: 12,
        name:"Wonderland",
        state:"Punjab",
        stars:"4.5",
        price:"High",
        city:"Jalandhar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.connectingtraveller.com/images/localtip/1630509082images%20(50).jpeg"
    },
    {
        id: 13,
        name:"Pushpa Gujral Science City",
        state:"Punjab",
        stars:"4.2",
        price:"Medium",
        city:"Jalandhar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://a.travel-assets.com/findyours-php/viewfinder/images/res70/68000/68140-Pushpa-Gujral-Science-City.jpg"
    },
    {
        id: 14,
        name:"Sheesh Mahal(Lahore fort)",
        state:"Punjab",
        stars:"4.0",
        price:"Low",
        city:"Patiala",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://lh3.googleusercontent.com/p/AF1QipPv21_Boa_XeDEKDl8wCJoLjU5h4fCZ05l0LTQ=w287-h192-n-k-rw-no-v1"
    },
    {
        id: 15,
        name:"Moti Bagh Palace",
        state:"Punjab",
        stars:"4.2",
        price:"Low",
        city:"Patiala",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://lh3.googleusercontent.com/p/AF1QipPNaaQYEWyG4D3X-ueOP8yDKDD9BZ8evx_WOOzh=w287-h192-n-k-rw-no-v1"
    },
    {
        id: 16,
        name:"Bhakra Nangal Dam",
        state:"Himachal Pradesh",
        stars:"4.4",
        price:"Low",
        city:"Jangal Mehduda Bhakhra",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.tripiwiki.com/images/places/uploads/Bhakra-Dam50227.jpg"
    },
    {
        id: 17,
        name:"Virasat-e-Khalsa",
        state:"Punjab",
        stars:"4.7",
        price:"Low",
        city:"Anandpur Sahib",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Khalsa_Heritage_Memorial_176_Edit.jpg/1200px-Khalsa_Heritage_Memorial_176_Edit.jpg"
    },
    {
        id: 18,
        name:"I.S.Bindra Stadium",
        state:"Punjab",
        stars:"4.7",
        price:"Medium",
        city:"Mohali",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn-wp.thesportsrush.com/2023/04/2dae01f8-mohali-cricket-stadium-last-10-matches.jpg"
    },
    {
        id: 19,
        name:"Nehru Kund",
        state:"Himachal Pradesh",
        stars:"4.4",
        price:"Low",
        city:"Manali",
        crowd:"Low",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://mysterioushimachal.files.wordpress.com/2023/04/compressed-xcuk.jpg?w=770"
    },
    {
        id: 20,
        name:"Mall Road",
        state:"Himachal Pradesh",
        stars:"4.0",
        price:"Medium",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://www.holidify.com/images/cmsuploads/raw/shutterstock_373549981_20190822151440.jpg"
    },
    {
        id: 21,
        name:"Rohtang Pass",
        state:"Himachal Pradesh",
        stars:"4.7",
        price:"Low",
        city:"Manali",
        crowd:"Low",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://www.kullumanalitrips.com/images/destination/himachal/solang-valley.jpg"
    },
    {
        id: 22,
        name:"Great Himalayan National Park",
        state:"Himachal Pradesh",
        stars:"4.5",
        price:"Medium",
        city:"Manali",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://www.sushanttravels.com/uploads/u5fE25p_Himalayan-Range-from-GHNP.jpg"
    },
    {
        id: 23,
        name:"Christ Church",
        state:"Himachal Pradesh",
        stars:"4.6",
        price:"Low",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/0f/81/d0/christ-church-shimla.jpg?w=1200&h=-1&s=1"
    },
    {
        id: 24,
        name:"Viceregal Lodge",
        state:"Himachal Pradesh",
        stars:"4.6",
        price:"Medium",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/ff/a4/24/viceregal-lodge-turned.jpg?w=1200&h=-1&s=1"
    },
    {
        id: 25,
        name:"Shri Hanuman Mandir Jakhoo",
        state:"Himachal Pradesh",
        stars:"4.8",
        price:"Medium",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://shimlatourism.co.in/images/places-to-visit/headers/jakhu-temple-shimla-tourism-entry-fee-timings-holidays-reviews-header.jpg"
    },
    {
        id: 26,
        name:"Red Fort(Lal Quila)",
        state:"Delhi",
        stars:"4.5",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn.britannica.com/20/189820-050-D650A54D/Red-Fort-Old-Delhi-India.jpg"
    },
    {
        id: 27,
        name:"Qutub Minar",
        state:"Delhi",
        stars:"4.5",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/b7/1f/31/qutab-minar.jpg?w=1200&h=1200&s=1"
    },
    {
        id: 28,
        name:"Taj Mahal",
        state:"Uttar Pradesh",
        stars:"5.0",
        price:"Low",
        city:"Agra",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn.britannica.com/86/170586-050-AB7FEFAE/Taj-Mahal-Agra-India.jpg"
    },
    {
        id: 29,
        name:"India Gate",
        state:"Delhi",
        stars:"4.6",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/0/09/India_Gate_in_New_Delhi_03-2016.jpg"
    },
    {
        id: 30,
        name:"Gurudwara Sri Bangla Sahib",
        state:"Delhi",
        stars:"4.8",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Front_view_of_Gurudwara_Bangla_Sahib%2C_Delhi.jpg/1200px-Front_view_of_Gurudwara_Bangla_Sahib%2C_Delhi.jpg"
    },
    {
        id: 31,
        name:"Lotus Temple",
        state:"Delhi",
        stars:"4.5",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/f/fc/LotusDelhi.jpg"
    },

]
