export default [
    {
        id: 1,
        name:"Sri Harminder Sahib",
        state:"Punjab",
        stars:"4.9",
        price:"Low",
        city:"Amritsar",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Z29sZGVuJTIwdGVtcGxlfGVufDB8fDB8fHww&w=1000&q=80"
    },
    {
        id: 2,
        name:"Jallianwala Bagh",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Amritsar",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://static.theprint.in/wp-content/uploads/2018/12/Panorama_of_Jallianwala_Bagh-e1550674910748.jpg"
    },
    {
        id: 3,
        name:"The Partition Museum",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Amritsar",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://amritsartourism.org.in/images/places-to-visit/headers/partition-museum-amritsar-tourism-entry-fee-timings-holidays-reviews-header.jpg"
    },
    {
        id: 4,
        name:"Wagah Border",
        state:"Punjab",
        stars:"4.0",
        price:"Low",
        city:"Amritsar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://amritsartourism.org.in/images/places-to-visit/headers/wagah-border-amritsar-tourism-entry-fee-timings-holidays-reviews-header.jpg"
    },
    {
        id: 5,
        name:"Maharaja Ranjit Singh War Museum",
        state:"Punjab",
        stars:"4.3",
        price:"Low",
        city:"Ludhiana",
        crowd:"low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.jagranimages.com/images/newimg/13082022/13_08_2022-maharaj_ranjit_singh_22977151.jpg"
    },
    {
        id: 6,
        name:"Rock Garden",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Chandigarh",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.citywoofer.com/blog/wp-content/uploads/2022/12/WhatsApp-Image-2022-12-13-at-11.34.17-PM.jpeg"
    },
    {
        id: 7,
        name:"Sukhna Lake",
        state:"Punjab",
        stars:"4.6",
        price:"Low",
        city:"Chandigarh",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.mapsofindia.com/ci-moi-images/my-india/sl-ch-punj-00051.jpg"
    },
    {
        id: 8,
        name:"Zakir Hussain Rose Garden",
        state:"Punjab",
        stars:"4.4",
        price:"Low",
        city:"Chandigarh",
        crowd:"low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/2/22/Rose_Garden_%2CChandigarh%2CIndia.jpg"
    },
    {
        id: 9,
        name:"Elante Mall",
        state:"Punjab",
        stars:"4.5",
        price:"Medium",
        city:"Chandigarh",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://singh-life.com/wp-content/uploads/2021/10/IMG_4781.jpg"
    },
    {
        id: 10,
        name:"Japenese Garden",
        state:"Punjab",
        stars:"4.3",
        price:"Low",
        city:"Chandigarh",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/5/5a/The_Japanese_Garden_Chandigarh_scenery.jpg"
    },
    {
        id: 11,
        name:"Devi Talab Mandir",
        state:"Punjab",
        stars:"4.7",
        price:"Low",
        city:"Jalandhar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn.holidaytravel.co/uploaded_files/destination_img/2016_1657efb450dd59cdevi-talab-jalandhar-tourist-guide.jpg"
    },
    {
        id: 12,
        name:"Wonderland",
        state:"Punjab",
        stars:"4.5",
        price:"High",
        city:"Jalandhar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.connectingtraveller.com/images/localtip/1630509082images%20(50).jpeg"
    },
    {
        id: 13,
        name:"Pushpa Gujral Science City",
        state:"Punjab",
        stars:"4.2",
        price:"Medium",
        city:"Jalandhar",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://a.travel-assets.com/findyours-php/viewfinder/images/res70/68000/68140-Pushpa-Gujral-Science-City.jpg"
    },
    {
        id: 14,
        name:"Sheesh Mahal(Lahore fort)",
        state:"Punjab",
        stars:"4.0",
        price:"Low",
        city:"Patiala",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://lh3.googleusercontent.com/p/AF1QipPv21_Boa_XeDEKDl8wCJoLjU5h4fCZ05l0LTQ=w287-h192-n-k-rw-no-v1"
    },
    {
        id: 15,
        name:"Moti Bagh Palace",
        state:"Punjab",
        stars:"4.2",
        price:"Low",
        city:"Patiala",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://lh3.googleusercontent.com/p/AF1QipPNaaQYEWyG4D3X-ueOP8yDKDD9BZ8evx_WOOzh=w287-h192-n-k-rw-no-v1"
    },
    {
        id: 16,
        name:"Bhakra Nangal Dam",
        state:"Himachal Pradesh",
        stars:"4.4",
        price:"Low",
        city:"Jangal Mehduda Bhakhra",
        crowd:"Low",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://www.tripiwiki.com/images/places/uploads/Bhakra-Dam50227.jpg"
    },
    {
        id: 17,
        name:"Virasat-e-Khalsa",
        state:"Punjab",
        stars:"4.7",
        price:"Low",
        city:"Anandpur Sahib",
        crowd:"Medium",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Khalsa_Heritage_Memorial_176_Edit.jpg/1200px-Khalsa_Heritage_Memorial_176_Edit.jpg"
    },
    {
        id: 18,
        name:"I.S.Bindra Stadium",
        state:"Punjab",
        stars:"4.7",
        price:"Medium",
        city:"Mohali",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn-wp.thesportsrush.com/2023/04/2dae01f8-mohali-cricket-stadium-last-10-matches.jpg"
    },
    {
        id: 19,
        name:"Nehru Kund",
        state:"Himachal Pradesh",
        stars:"4.4",
        price:"Low",
        city:"Manali",
        crowd:"Low",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://mysterioushimachal.files.wordpress.com/2023/04/compressed-xcuk.jpg?w=770"
    },
    {
        id: 20,
        name:"Mall Road",
        state:"Himachal Pradesh",
        stars:"4.0",
        price:"Medium",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://www.holidify.com/images/cmsuploads/raw/shutterstock_373549981_20190822151440.jpg"
    },
    {
        id: 21,
        name:"Rohtang Pass",
        state:"Himachal Pradesh",
        stars:"4.7",
        price:"Low",
        city:"Manali",
        crowd:"Low",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://www.kullumanalitrips.com/images/destination/himachal/solang-valley.jpg"
    },
    {
        id: 22,
        name:"Great Himalayan National Park",
        state:"Himachal Pradesh",
        stars:"4.5",
        price:"Medium",
        city:"Manali",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://www.sushanttravels.com/uploads/u5fE25p_Himalayan-Range-from-GHNP.jpg"
    },
    {
        id: 23,
        name:"Christ Church",
        state:"Himachal Pradesh",
        stars:"4.6",
        price:"Low",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/0f/81/d0/christ-church-shimla.jpg?w=1200&h=-1&s=1"
    },
    {
        id: 24,
        name:"Viceregal Lodge",
        state:"Himachal Pradesh",
        stars:"4.6",
        price:"Medium",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0b/ff/a4/24/viceregal-lodge-turned.jpg?w=1200&h=-1&s=1"
    },
    {
        id: 25,
        name:"Shri Hanuman Mandir Jakhoo",
        state:"Himachal Pradesh",
        stars:"4.8",
        price:"Medium",
        city:"Shimla",
        crowd:"Medium",
        landscape:"Mountains",
        description: "lorem impus dolor sit amet",
        url:"https://shimlatourism.co.in/images/places-to-visit/headers/jakhu-temple-shimla-tourism-entry-fee-timings-holidays-reviews-header.jpg"
    },
    {
        id: 26,
        name:"Red Fort(Lal Quila)",
        state:"Delhi",
        stars:"4.5",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn.britannica.com/20/189820-050-D650A54D/Red-Fort-Old-Delhi-India.jpg"
    },
    {
        id: 27,
        name:"Qutub Minar",
        state:"Delhi",
        stars:"4.5",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/b7/1f/31/qutab-minar.jpg?w=1200&h=1200&s=1"
    },
    {
        id: 28,
        name:"Taj Mahal",
        state:"Uttar Pradesh",
        stars:"5.0",
        price:"Low",
        city:"Agra",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://cdn.britannica.com/86/170586-050-AB7FEFAE/Taj-Mahal-Agra-India.jpg"
    },
    {
        id: 29,
        name:"India Gate",
        state:"Delhi",
        stars:"4.6",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/0/09/India_Gate_in_New_Delhi_03-2016.jpg"
    },
    {
        id: 30,
        name:"Gurudwara Sri Bangla Sahib",
        state:"Delhi",
        stars:"4.8",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Front_view_of_Gurudwara_Bangla_Sahib%2C_Delhi.jpg/1200px-Front_view_of_Gurudwara_Bangla_Sahib%2C_Delhi.jpg"
    },
    {
        id: 31,
        name:"Lotus Temple",
        state:"Delhi",
        stars:"4.5",
        price:"Low",
        city:"Delhi",
        crowd:"High",
        landscape:"Plains",
        description: "lorem impus dolor sit amet",
        url:"https://upload.wikimedia.org/wikipedia/commons/f/fc/LotusDelhi.jpg"
    },
    {
        id: 32,
        name:"Ajanta Ellora Caves",
        state:"Maharashtra",
        stars:"4",
        price:"Low",
        city:"Aurangabad",
        crowd:"Medium",
        landscape:"Plateaus",
        description: "lorem impus dolor sit amet",
        url:"https://breathedreamgo.com/ellora-and-ajanta-caves-surprisingly-stupendous/"
    },
        {
            "id": 33 ,
            "name": "Gateway Of India Mumbai",
            "state": "Maharashtra",
            "stars": 4.6,
            "price": "low",
            "city": "Mumbai",
            "crowd": "high",
            "landscape": "coastal",
            "description": "",
            "url": "https:\/\/www.trawell.in\/admin\/images\/upload\/955980144Mumbai_Gateway_India_Main.jpg"
        },
        {
            "id": 34,
            "name": "Chhatrapati Shivaji Maharaj Terminus",
            "state": "Maharashtra",
            "stars": 4.5,
            "price": "low",
            "city": "Mumbai",
            "crowd": "high",
            "landscape": "coastal",
            "description": "lorem50",
            "url": "https:\/\/planetofhotels.com\/guide\/sites\/default\/files\/styles\/paragraph__hero_banner__hb_image__1880bp\/public\/hero_banner\/station.jpg"
        },
        {
            "id": 35 ,
            "name": "Elephanta Caves",
            "state": "Maharashtra",
            "stars": 4.3,
            "price": "medium",
            "city": "Mumbai",
            "crowd": "medium",
            "landscape": "plateaus",
            "description": "lorem50",
            "url": "https:\/\/www.holidify.com\/images\/cmsuploads\/compressed\/shutterstock_694433434_20191213110339_20191213110412.png"
        },
        {
            "id": 36 ,
            "name": "Haji Ali Dargah",
            "state": "Maharashtra",
            "stars": 4.4,
            "price": "low",
            "city": "Mumbai",
            "crowd": "medium",
            "landscape": "coastal",
            "description": null,
            "url": "https:\/\/static.toiimg.com\/thumb\/64061841\/Haji-Ali-Dargah-all-that-you-need-to-know-about-this-floating-wonder.jpg?width=1200&height=900"
        },
        {
            "id": 37 ,
            "name": "Shree Siddhivinayak Temple",
            "state": "Maharashtra",
            "stars": 4.7,
            "price": "low",
            "city": "Mumbai",
            "crowd": "high",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/www.mapsofindia.com\/ci-moi-images\/my-india\/siddhivinayak-temple-mumbai-1024x871.jpg"
        },
        {
            "id": 38 ,
            "name": "Marine Drive",
            "state": "Maharashtra",
            "stars": 4.6,
            "price": "medium",
            "city": "Mumbai",
            "crowd": "medium",
            "landscape": "coastal",
            "description": null,
            "url": "https:\/\/static01.nyt.com\/images\/2019\/10\/21\/travel\/21mumbai-walkingtour2\/merlin_162106725_227c3804-2c41-4f0d-a350-bf638b184ca1-articleLarge.jpg?quality=75&auto=webp&disable=upscale"
        },
        {
            "id": 39 ,
            "name": "Juhu Beach",
            "state": "Maharashtra",
            "stars": 3.5,
            "price": "medium",
            "city": "Mumbai",
            "crowd": "medium",
            "landscape": "coastal",
            "description": null,
            "url": "https:\/\/a.travel-assets.com\/findyours-php\/viewfinder\/images\/res70\/111000\/111503-Juhu-Beach.jpg"
        },
        {
            "id": 40 ,
            "name": "Lalbagh Botanical Garden",
            "state": "Karnataka",
            "stars": 4.4,
            "price": "medium",
            "city": "Bengaluru",
            "crowd": "medium",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/content.r9cdn.net\/rimg\/dimg\/27\/f6\/bc3bb5e9-lm-48436-172b5c9131e.jpg?width=1366&height=768&xhint=1499&yhint=494&crop=true"
        },
        {
            "id": 41 ,
            "name": "Cubbon Park",
            "state": "Karnataka",
            "stars": 4.4,
            "price": "low",
            "city": "Bengaluru",
            "crowd": "high",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/thewire.in\/wp-content\/uploads\/2016\/12\/bandstand.jpg"
        },
        {
            "id": 42 ,
            "name": "ISKCON temple bangalore",
            "state": "Karnataka",
            "stars": 4.6,
            "price": "low",
            "city": "Bengaluru",
            "crowd": "high",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/www.iskconbangalore.org\/wp-content\/uploads\/2016\/01\/g01-night-view-of-iskcon-bangalore.jpg"
        },
        {
            "id": 43 ,
            "name": "Bengaluru Palace",
            "state": "Karnataka",
            "stars": 4.2,
            "price": "high",
            "city": "Bengaluru",
            "crowd": "medium",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/bangaloretourism.in\/images\/v2\/headers\/bangalore-palace-timings-entry-fee-bangalore-tourism-header-cr-amit-rawat.jpg"
        },
        {
            "id": 44 ,
            "name": "Vidhana Saudha",
            "state": "Karnataka",
            "stars": 4.6,
            "price": "low",
            "city": "Bengaluru",
            "crowd": "medium",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/encrypted-tbn0.gstatic.com\/images?q=tbn:ANd9GcSQj5oqxg3QBgl7wJc3EATSRLRmUM-H00Ruhg&usqp=CAU"
        },
        {
            "id": 45 ,
            "name": "Bannerghata Biological Park",
            "state": "Karnataka",
            "stars": 4.4,
            "price": "high",
            "city": "Bengaluru",
            "crowd": "low",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/www.holidify.com\/images\/compressed\/4130.JPG"
        },
        {
            "id": 46 ,
            "name": "Jawaharlal Nehru Planeterium",
            "state": "Karnataka",
            "stars": 4.4,
            "price": "medium",
            "city": "Bengaluru",
            "crowd": "medium",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/www.taralaya.org\/images\/skytheatre.jpg"
        },
        {
            "id": 47 ,
            "name": "St. Mary 's Basilica",
            "state": "Karnataka",
            "stars": 4.6,
            "price": "low",
            "city": "Bengaluru",
            "crowd": "low",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/www.holidify.com\/images\/cmsuploads\/compressed\/ScreenShot2020-04-16at4.17.34PM_20200416161841.png"
        },
        {
            "id": 48 ,
            "name": "Santhome Cathedral Basilica",
            "state": "Tamil Nadu",
            "stars": 4.7,
            "price": "low",
            "city": "Chennai",
            "crowd": "low",
            "landscape": "plains",
            "description": null,
            "url": "https:\/\/catholicshrinebasilica.com\/wp-content\/uploads\/2021\/12\/santhome.jpg"
        },
        {
            "id": 49 ,
            "name": "Fort St. George Museum",
            "state": "Tamil Nadu",
            "stars": 4.2,
            "price": "low",
            "city": "Chennai",
            "crowd": "medium",
            "landscape": "coastal",
            "description": null,
            "url": "Jawaharlal Nehru Planeterium"
        },
        {
            "id": 50 ,
            "name": "Kapaleeshwarar Temple",
            "state": "Tamil Nadu",
            "stars": 4.8,
            "price": "medium",
            "city": "Chennai",
            "crowd": "high",
            "landscape": "coastal",
            "description": null,
            "url": "https:\/\/ticketnews.in\/wp-content\/uploads\/2023\/05\/fort-st-george-tickets.webp"
        },
        {
            "id": 51 ,
            "name": "Government Museum Chennai",
            "state": "Tamil Nadu",
            "stars": 4.3,
            "price": "medium",
            "city": "Chennai",
            "crowd": "medium",
            "landscape": "plateaus",
            "description": null,
            "url": "https:\/\/chennaitourism.travel\/images\/places-to-visit\/headers\/chennai-government-museum-tourism-entry-fee-timings-holidays-reviews-header.jpg"
        },
        {
            "id": 52 ,
            "name": "Guindy National Park",
            "state": "Tamil Nadu",
            "stars": 4.1,
            "price": "medium",
            "city": "Chennai",
            "crowd": "low",
            "landscape": "coastal",
            "description": null,
            "url": "https:\/\/chennaitourism.travel\/images\/places-to-visit\/headers\/guindy-national-park-chennai-tourism-entry-fee-timings-holidays-reviews-header.jpg"
        },
        {
            "id": 53 ,
            "name": "Marina Beach",
            "state": "Tamil Nadu",
            "stars": 4.3,
            "price": "low",
            "city": "Chennai",
            "crowd": "medium",
            "landscape": "plains",
            "description": null,
            "url": "https:\/\/chennaitourism.travel\/images\/places-to-visit\/headers\/marina-beach-chennai-tourism-entry-fee-timings-holidays-reviews-header.jpg"
        },
        {
            "id": 54 ,
            "name": "DakshinaCHitra Heritage Museum",
            "state": "Tamil Nadu",
            "stars": 4.4,
            "price": "medium",
            "city": "Chennai",
            "crowd": "medium",
            "landscape": "coastal",
            "description": null,
            "url": "holidify.com\/images\/cmsuploads\/compressed\/Dakshinachitra-Muttukadu_20180212125820.jpg"
        },
        {
            "id": 55 ,
            "name": "Shri Ashtakalshmi Temple",
            "state": "Tamil Nadu",
            "stars": 4.6,
            "price": "low",
            "city": "Chennai",
            "crowd": "high",
            "landscape": "plateaus",
            "description": null,
            "url": "dynamic-media-cdn.tripadvisor.com\/media\/photo-o\/0c\/15\/94\/f3\/stunning-views.jpg?w=1200&h=1200&s=1"
        },
        {
            "id": 56 ,
            "name": "Edward Elliot 's Beach",
            "state": "Tamil Nadu",
            "stars": 4.4,
            "price": "low",
            "city": "Chennai",
            "crowd": "low",
            "landscape": "coastal",
            "description": null,
            "url": "chennaitourism.travel\/images\/places-to-visit\/headers\/edward-elliot-s-beach-chennai-tourism-entry-fee-timings-holidays-reviews-header.jpg"
        },
        {
            "id": 57 ,
            "name": "B.M. Birla Planetarium",
            "state": "Tamil Nadu",
            "stars": 4.1,
            "price": "low",
            "city": "Chennai",
            "crowd": "low",
            "landscape": "coastal",
            "description": null,
            "url": "tnstc.gov.in\/images\/demo\/home\/Anna_Home.jpg"
        }
]
